[package]
name = "ipkg"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
colored = "3.0.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_toml = "0.0.1"
serde_yaml = "0.9.34"
thiserror = "2.0.12"
